const CONSTANT = {
  FINISH: Symbol.for('finish'),
  CURRENT: Symbol.for('current'),
  NORMAL: Symbol.for('normal'),
  START: Symbol.for('start'),
  PAUSE: Symbol.for('pause'),
  STOP: Symbol.for('stop'),
  PLAY: Symbol.for('play'),
  OVER: Symbol.for('over'),
  CORRECT: Symbol.for('correct'),
  WRONG: Symbol.for('wrong'),
  RIGHT: Symbol.for('right'),
  ENABLE: Symbol.for('enable'),
  DISABLE: Symbol.for('disable'),
  OPEN: Symbol.for('open'),
  CLOSE: Symbol.for('close'),
  END: Symbol.for('end'),
  TIME_OUT: Symbol.for('timeOut'),
  ADD_SCORE: Symbol.for('addScore'),
  FULL_SCORE: Symbol.for('fullScore'),
  DESTROY: Symbol.for('destroy'),
  DEFAULT_FONT: 'Century Gothic',
  DEFAULT_FONT_12: '12px Century Gothic',
  DEFAULT_FONT_16: '16px Century Gothic',
  DEFAULT_FONT_18: '18px Century Gothic',
  DEFAULT_FONT_20: '20px Century Gothic',
  DEFAULT_FONT_22: '22px Century Gothic',
  DEFAULT_FONT_24: '24px Century Gothic',
  DEFAULT_FONT_32: '32px Century Gothic',
  DEFAULT_FONT_34: '34px Century Gothic',
  DEFAULT_FONT_42: '42px Century Gothic',
  DEFAULT_FONT_46: '46px Century Gothic',
  DEFAULT_FONT_58: '58px Century Gothic',
  SOUND: 'sound',
  VIDEO: 'video',
  VIDEOS: 'videos',
  SOUNDS: 'sounds',
  SOUND_OBJ: 'soundobj',
  IMAGE: 'image',
  IMAGES: 'images',
  IMAGE_OBJ: 'imageobj',
  JSON: 'json',
  JSONS: 'jsons',
  XML: 'xml',
  XMLS: 'xmls',
  VIDEO_PLAY: Symbol(),
  VIDEO_SCALE: 2.5
};

export { CONSTANT };